FROM lab/ros:base

RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-desktop \
                                         apt-transport-https \
                                         ca-certificates \
                                         wget \
                                         gnupg \
                                         libnss3 \
                                         libxkbfile1 \
                                         libgconf-2-4 \
                                         libsecret-1-0 \
                                         libxss1 \
                                         libasound2 \
                                         --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

#RUN apt-get update && apt-get install -y eclipse-cdt && \
#    rm -fr /var/lib/apt/lists/*

RUN wget -O /tmp/vscode.deb https://projects.cdn.cynt4k.de/autonomous-racecar/vscode_arm64.deb && dpkg -i /tmp/vscode.deb && rm /tmp/vscode.deb

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:rosdev' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

ADD scripts/ros_entrypoint.sh /ros_entrypoint.sh
CMD ["/usr/sbin/sshd", "-D"]
