version: '3.1'

services:
  dev:
    build: .
    image: lab/ros:dev
    container_name: dev
    environment:
    - DISPLAY=$DISPLAY
    - ROS_HOSTNAME=tegra-ubuntu
    - ROS_IP=172.18.1.1
    - ROS_MASTER_URI=http://core:11311
    volumes:
    - "${HOME}/.Xauthority:/root/.Xauthority"
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    cap_add:
    - SYS_PTRACE
    network_mode: "host"
    privileged: true
    command: tail -f /dev/null

  dns:
    image: lab/devdns
    container_name: rosdns
    ports:
    - 53:53/udp
    environment:
    - DNS_DOMAIN=ros
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - ros

networks:
  ros:
    external: true
