version: '3.1'

services:
  tf-publish:
    build: .
    image: lab/tf-publish:latest
    container_name: tf-publish
    environment:
    - ROS_HOSTNAME=tf-publish
    - ROS_MASTER_URI=http://core:11311
    cap_add:
    - SYS_PTRACE
    networks:
    - ros
    #command: tail -f /dev/null
    command: roslaunch tf-publish tf-publish.launch

networks:
  ros:
    external: true
