frequency: 20

odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: odom

odom0_config : [ true, true, false,
                 false, false, false,
                 false, false, false,
                 false, false, true,
                 false, false, false ]

odom0_queue_size: 2

imu0: imu

imu0_config: [ false, false, false,
               true, true, true,
               false, false, false,
               true, true, true,
               true, true, true ]

imu0_queue_size: 5

